export const CHARACTERS_ACTIONS_CONSTANTS = {
    GET_CHARACTERS: 'GET_CHARACTERS',
    GET_CHARACTERS_SUCCESS: 'GET_CHARACTERS_SUCCESS',
    GET_CHARACTERS_ERROR: 'GET_CHARACTERS_ERROR',
    GET_CHARACTER: 'GET_CHARACTER',
    GET_CHARACTER_SUCCESS: 'GET_CHARACTER_SUCCESS'
} as const;